@startuml changeProduct

actor User

User -> ProductTable : change product

alt 2XX request
    ProductTable -> User : return OK message
else 4XX request
    ProductTable -> User : return ERROR message
end

@enduml