@startuml ChangeSaleCompositionTable

actor User

User -> SaleCompositionTable : change composition

alt 2XX request
    SaleCompositionTable -> User : return OK message
else 4XX request
    SaleCompositionTable -> User : return ERROR message
end

@enduml